<section class="registration">
    <div class="container" id="roles">
        <h2>Registration</h2>
        <form class="registration_form" method="POST">
            <div class="form-group">
                <input type="text"
                       class="form-control"
                       placeholder="host"
                       name="host"
                       required/>
                <input type="text"
                       class="form-control"
                       placeholder="user"
                       name="user"
                       required/>
                <input type="text"
                       class="form-control"
                       placeholder="password"
                       name="password"
                       required/>
                <input type="text"
                       class="form-control"
                       placeholder="database"
                       name="database"
                       required/>
            </div>
            <input type="submit" value="Start">
        </form>
    </div>
</section>